### ISSUE TITLE
Sync XHR issue

### ISSUE THREAD

**Issue by septs** [dfahlander/typeson-registry#19]
Disallow sync XHR in page dismissal
see https://chromestatus.com/feature/4664843055398912

Feature Policy: control Synchronous XMLHttpRequest
see https://chromestatus.com/feature/5154875084111872

Conclusion: I think should be remove **Sync XHR**

**Comment by brettz9** [comment]
Yes, it's been deprecated for a while, but since the user can opt to use the async API anyways, I don't think it would be advisable to remove it at this point. https://chromestatus.com/feature/4664843055398912 mentions sync XHR being on a deprecation path, but neither of those remove it, and one can't be sure that it will definitely be removed (e.g., there might end up being too many sites that continue to use it for them to decide to definitely remove it).

We are still using the synchronous API in IndexedDBShim because unless such a change definitely occurs, switching to the async API will add a performance cost to each use of the structured cloning algorithm (which is frequent), and not only for cases when a Blob or such is in use (i.e., the API always requires waiting for a microtask).
